git:
  commitMessage: "[chore] Release v${version}"
  requireBranch: main
github:
  release: true
  web: true
  releaseName: "${version}: "
npm:
  publish: false
hooks:
  before:bump:
    - cd ../js && npm i && npm run build
  after:bump:
    - cd ../js && npm i
    - git add ../js/package.json ../js/package-lock.json ../src/Util.php
  after:release: "echo Successfully released ${name} v${version} to ${repo.repository}."
plugins:
  "@release-it/bumper":
    in: package.json
    out:
      - ../src/Util.php
      - ../js/package.json

