git:
  commitMessage: "[chore] Release v${version}"
  requireBranch: main
github:
  release: true
  web: true
  releaseName: "${version}: "
npm:
  publish: false
hooks:
  after:release: "echo Successfully released ${name} v${version} to ${repo.repository}."
plugins:
  "@release-it/bumper":
    in: util/package.json
    out:
      file: src/Util.php
      type: text/php
